services:
  backend:
    image: ghcr.io/zhouzhou12203/easypaper-backend:main
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./backend/config:/app/config
      - ./backend/data:/app/data
      - ./backend/tmp:/app/tmp
      - ./backend/logs:/app/logs
    environment:
      - APP_CONFIG_PATH=/app/config/config.yaml
      - HF_ENDPOINT=https://hf-mirror.com
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/zhouzhou12203/easypaper-frontend:main
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
